name: CI-CD-EKS

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write    # NECESSÁRIO para OIDC
  contents: read     # Para checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::925445554210:role/GitHubActionsEKSRole
          aws-region: us-east-1

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-eks:latest .

      - name: Push imagem Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-eks:latest

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Configurar kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name eks-devops

      - name: Deploy k8s
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
