name: CI-CD-EKS

on:
  push:
    branches: [ "main" ]

# Necessário para permitir OIDC
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Autenticação via OIDC (SEM ACCESS KEYS)
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::925445554210:role/GitHubActionsEKSRole
          aws-region: us-east-1

      # Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Buildx é obrigatório no GitHub Actions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build com contexto explícito (solução 2)
      - name: Build da imagem Docker
        run: docker buildx build --load -t ${{ secrets.DOCKERHUB_USERNAME }}/api-eks:latest --file Dockerfile .

      # Push da imagem para o Docker Hub
      - name: Push imagem Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-eks:latest

      # Instalar Terraform
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # Terraform Apply para criar EKS + VPC
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      # Configurar kubectl para acessar o cluster
      - name: Configurar kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name eks-devops

      # Aplicar manifestos no Kubernetes
      - name: Deploy k8s
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
