name: CI-CD-EKS

on:
  push:
    branches: [ "main" ]

# Necessário para OIDC
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Autenticação AWS via OIDC (SEM ACCESS KEYS)
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::925445554210:role/GitHubActionsEKSRole
          aws-region: us-east-1

      # Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: felipec23
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Buildx obrigatório
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build usando Dockerfile da raiz + contexto explícito
      - name: Build da imagem Docker
        run: docker buildx build --load -t felipec23/api-eks:latest --file Dockerfile .

      # Push da imagem
      - name: Push imagem Docker
        run: docker push felipec23/api-eks:latest

      # Instalar Terraform
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # Terraform Apply para criar EKS
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      # Configurar kubectl
      - name: Configurar kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name eks-devops

      # Deploy para o Kubernetes
      - name: Deploy no Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
